version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    networks:
      - dockernet
    ports:
      - "5433:5432"

  app:
    image: ${DOCKER_REGISTRY-}app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - AUTH0_CLIENT_ID=123123
      - AUTH0_CLIENT_SECRET=123
      - GMAIL_USER_NAME=test@gmail.com
      - GMAIL_PASSWORD=halla
      - CLOUDINARY_URL=noe
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - dockernet
    ports:
      - "8081:8080"

networks:
  dockernet:
