version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    networks:
      - dockernet
    ports:
      - "5433:5432"

  app:
    image: lassekl/gata:test
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - CLOUDINARY_URL=noe
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - GATA_MAKE_FIRST_USER_ADMIN=${GATA_MAKE_FIRST_USER_ADMIN}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - VITE_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    networks:
      - dockernet
    ports:
      - "8080:8080"
    depends_on:
      - db

networks:
  dockernet:
