version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    networks:
      - dockernet
    ports:
      - "5433:5432"

  backend-app:
    image: lassekl/gatabackend:test
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - CLOUDINARY_URL=${CLOUDINARY_URL:-NA}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-NA}
      - GATA_MAKE_FIRST_USER_ADMIN=true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dockernet
    depends_on:
      - db

networks:
  dockernet:
