name: 'Deploy frontend'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./gata-frontend
          push: true
          tags: lassekl/gatafrontend:${{ github.sha }}

      - name: Push frontend to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@gataersamla.no:22/gata'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: lassekl/gatafrontend:${{ github.sha }}
