name: 'Deploy backend'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'gata-frontend/**'
      - 'gata-tests/**'
      - '.github/**'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lassekl/gatabackend:${{ github.sha }}

      - name: Push backend to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@api.gataersamla.no:22/gatabackend'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: lassekl/gatabackend:${{ github.sha }}
