name: Migrate db

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    env:
      APP_DATABASE_URL: ${{ secrets.APP_PROD_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Migrate with drizzle
        run: |
          npm run db:migrate
